### PR TITLE
demangle: raise ValueError on string formatting issues as well

### LINKED ISSUE #8: Unexpected error on malformed mangled names
### Background Info

We've recently come across a binary with what appears to be a malformed symbol name that would trigger the following exception:

```
thread '<unnamed>' panicked at 'a Display implementation returned an error unexpectedly: Error', /rustc/897e37553bba8b42751c67658967889d11ecd120/library/alloc/src/string.rs:2511:14
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
pyo3_runtime.PanicException: a Display implementation returned an error unexpectedly: Error
```

### Reproduction

You can reproduce it with the Python lines below:

```python
from cpp_demangle import demangle

demangle('_ZSt11make_sharedI16group_record_msgIRjR22mcast_addr_record_typeR12addr_storageSt3setI6sourceSt4lessIS7_ESaIS7_EE18group_mem_protocolEESt10shared_ptrIT_EDpOT0_')
```

This symbol name is _really_ close to the other one, but this time it works:

```python
from cpp_demangle import demangle

demangle('_ZSt11make_sharedI16group_record_msgJRjR22mcast_addr_record_typeR12addr_storageSt3setI6sourceSt4lessIS7_ESaIS7_EE18group_mem_protocolEESt10shared_ptrIT_EDpOT0_')
```

The only difference is the character at index 38 (a `J` in the valid one, a `I` in the invalid one, which looks like a bit flip. I'm currently investigating to see if it's the ELF parser or the file that got flipped.

### Recommendation

Would it be possible to raise a `ValueError` instead of the `PanicException` on such cases ?

### PR DESCRIPTION
**Pull request by vlaci**
In `cpp_demangle`, `ToString` is implemented via the blanket implementation of `Display`, which is [fallible](https://github.com/gimli-rs/cpp_demangle/blob/master/src/lib.rs#L451-L454), 

Resolves #8

### CODE REVIEW

**Review by benfred — APPROVED** [review]
looks good! thanks for the fix.

**Comment by vlaci** [comment]
Looking into fixing the tests.

**Comment by vlaci** [comment]
Everything should be all right now.

**Comment by qkaiser** [comment]
@benfred can you merge it ? :)

**Comment by benfred** [comment]
thanks everyone!

**Comment by benfred** [comment]
There is a new release with this change up on pypi https://pypi.org/project/cpp-demangle/0.1.2/

**Pull request merged**
